export enum PermissionKey {
    PostBook = 'create_book',
    DeleteBook = 'delete_book',
    ViewBook = 'view_book',
    UpdateBook = 'update_book',
    ViewAuthor = 'view_author',
    PostAuthor = 'create_author',
    DeleteAuthor = 'delete_author',
    UpdateAuthor = 'update_author',
    ViewCategory = 'view_category',
    PostCategory = 'create_category',
    DeleteCategory = 'delete_category',
    UpdateCategory = 'update_category',
    ViewUser = 'view_user',
    DeleteUser = 'delete_user',
    PostUser = 'create_user',
    PostAdmin = 'create_admin',
  }